[tool.poetry]
name = "2lesson"
version = "0.1.0"
description = ""
authors = ["artem <harchenkoart@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
